name: CI

on: [push]

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v2
        with:
          go-version: 1.14

      - run: go get -v -t -d ./...
      - run: go test ./...
      - run: go build -v .
      - run: go vet
      - run: test -z $(gofmt -l .)

  docker-build:
    name: Build Docker image (smoke test)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - run: docker build .
