name: Integration

on:
  push:
  schedule:
    - cron: "0 0 * * *"

jobs:
  integration:
    name: Integration
    runs-on: ubuntu-latest

    steps:
      - uses: kvrhdn/gha-buildevents@main
        with:
          apikey: ${{ secrets.BUILDEVENT_APIKEY }}
          dataset: tfe-run_integration
          job-status: ${{ job.status }}

      - uses: actions/checkout@v3

      - name: Start step 'speculative-plan'
        run: |
          echo "STEP_ID=0" >> $GITHUB_ENV
          echo "STEP_START=$(date +%s)" >> $GITHUB_ENV

      - uses: ./
        with:
          token: ${{ secrets.TFE_TOKEN }}
          workspace: tfe-run_integration
          type: plan
          wait-for-completion: true
          tf-vars: |
            run_number = ${{ github.run_number }}
        id: plan

      - name: Assert speculative plan has changes
        if: steps.plan.outputs.has-changes == 'false'
        run: |
          echo "Expected speculative plan to have changes, but had not"
          exit 1

      - name: Wrap up step
        run: |
          buildevents step $TRACE_ID $STEP_ID $STEP_START speculative-plan

      - name: Start step 'apply'
        run: |
          echo "STEP_ID=1" >> $GITHUB_ENV
          echo "STEP_START=$(date +%s)" >> $GITHUB_ENV

      - uses: ./
        with:
          token: ${{ secrets.TFE_TOKEN }}
          workspace: tfe-run_integration
          message: "Integration run ${{ github.run_number }}"
          type: apply
          wait-for-completion: true
          tf-vars: |
            run_number = ${{ github.run_number }}
        id: apply

      - name: Assert run number is published to S3
        env:
          RUN_NUMBER: ${{ github.run_number }}
          S3_URL: ${{ steps.apply.outputs.tf-endpoint }}
        run: |
          EXPECTED="GitHub Actions run number: $RUN_NUMBER"
          ACTUAL=$(curl $S3_URL)

          if [ "$EXPECTED" != "$ACTUAL" ]; then
            echo "Data on S3 does not match with expectations!"
            echo ""
            echo "Got:      '$ACTUAL'"
            echo "Expected: '$EXPECTED'"
            exit 1
          fi

      - name: Wrap up step
        run: |
          buildevents step $TRACE_ID $STEP_ID $STEP_START apply

      - name: Start step 'destroy'
        run: |
          echo "STEP_ID=2" >> $GITHUB_ENV
          echo "STEP_START=$(date +%s)" >> $GITHUB_ENV

      - uses: ./
        with:
          token: ${{ secrets.TFE_TOKEN }}
          workspace: tfe-run_integration
          message: "Integration run ${{ github.run_number }} - destroy"
          type: destroy
          targets: |
            aws_s3_bucket_object.index
            aws_s3_bucket_object.error
          wait-for-completion: true
          tf-vars: |
            run_number = ${{ github.run_number }}
        id: destroy

      - name: Wrap up step
        run: |
          buildevents step $TRACE_ID $STEP_ID $STEP_START destroy
